type: "orchestration"
version: "1.0"
pipeline:
  metadata:
    description: "create product source tables"
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Create_table_src_products"
        - "Create_table_src_prod_cost"
      skipped: false
      parameters:
        componentName: "Start 0"
    Create_table_src_products:
      type: "create-table-v2"
      transitions:
        success:
        - "And_Tables_Creation"
      skipped: false
      parameters:
        componentName: "Create_table_src_products"
        createMethod: "Create if not exists"
        database: "[Environment Default]"
        schema: "SOURCE"
        table: "SRC_PRODUCTS"
        snowflakeTableType: "Permanent"
        columns:
        - - "PRODUCT_ID"
          - "number"
          - "9"
          - "0"
          - ""
          - "Yes"
          - "No"
          - "No"
        - - "GROUP_ID"
          - "number"
          - "9"
          - "0"
          - ""
          - "No"
          - "No"
          - ""
        - - "PRODUCT_DESC"
          - "varchar"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "GROUP_DESC"
          - "varchar"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "DIVISION_DESC"
          - "varchar"
          - "20"
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation: ""
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
    Create_table_src_prod_cost:
      type: "create-table-v2"
      transitions:
        success:
        - "And_Tables_Creation"
      skipped: false
      parameters:
        componentName: "Create_table_src_prod_cost"
        createMethod: "Create if not exists"
        database: "[Environment Default]"
        schema: "SOURCE"
        table: "SRC_PRODUCT_COST"
        snowflakeTableType: "Permanent"
        columns:
        - - "PRODUCT_CODE"
          - "number"
          - "9"
          - "0"
          - ""
          - "Yes"
          - "No"
          - "No"
        - - "SUPPLIER_DESC"
          - "varchar"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "COMPONENT_ID"
          - "varchar"
          - "30"
          - ""
          - ""
          - "No"
          - "No"
          - ""
        - - "COST"
          - "NUMBER"
          - "9"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation: ""
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
    And_Tables_Creation:
      type: "and"
      transitions:
        unconditional:
        - "RDS_src_products"
        - "RDS_src_product_cost"
      skipped: false
      parameters:
        componentName: "And_Tables_Creation"
    RDS_src_product_cost:
      type: "rds-query"
      transitions:
        unconditional:
        - "And_Tables_Load"
      skipped: false
      parameters:
        componentName: "RDS_src_product_cost"
        basicAdvancedMode: "Advanced"
        databaseType: "mysql"
        rdsEndpoint: "mysql-mkm.cyalkxt4axz9.us-west-2.rds.amazonaws.com:3306"
        databaseName: "srcdbu"
        username: "admin"
        password: ""
        sqlQuery: "select * from SRC_PRODUCT_COST"
        jdbcOptions:
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SOURCE"
        targetTable: "SRC_PRODUCT_COST"
        stage: "[Custom]"
        stagePlatform: "Existing Amazon S3 Location"
        stageAuthentication: "Credentials"
        s3StagingArea: "mkmotors/Mat_Stage"
        useAcceleratedEndpoint: "False"
        encryption: "None"
        concurrency: "1"
        loadOptions:
        - "On"
        - "Off"
        - "Off"
        - ""
        - "On"
        - "Gzip"
    RDS_src_products:
      type: "rds-query"
      transitions:
        unconditional:
        - "And_Tables_Load"
      skipped: false
      parameters:
        componentName: "RDS_src_products"
        basicAdvancedMode: "Advanced"
        databaseType: "mysql"
        rdsEndpoint: "mysql-mkm.cyalkxt4axz9.us-west-2.rds.amazonaws.com:3306"
        databaseName: "srcdbu"
        username: "admin"
        password: ""
        sqlQuery: "select * from SRC_PRODUCTS"
        jdbcOptions:
        - - ""
          - ""
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SOURCE"
        targetTable: "SRC_PRODUCTS"
        stage: "[Custom]"
        stagePlatform: "Existing Amazon S3 Location"
        stageAuthentication: "Credentials"
        s3StagingArea: "mkmotors/Mat_Stage/"
        useAcceleratedEndpoint: "False"
        encryption: "None"
        concurrency: "2"
        loadOptions:
        - "On"
        - "Off"
        - "On"
        - ""
        - "On"
        - "Gzip"
    Rewrite_products 0:
      type: "run-transformation"
      skipped: false
      parameters:
        componentName: "Rewrite_products 0"
        transformationJob: "Training_BlackCloud/rewrite_stg_products_from_src"
        setScalarVariables:
        setGridVariables:
    And_Tables_Load:
      type: "and"
      transitions:
        unconditional:
        - "Rewrite_products 0"
      skipped: false
      parameters:
        componentName: "And_Tables_Load"
design:
  components:
    Start 0:
      position:
        x: -352
        "y": -16
      tempMetlId: 328
    Create_table_src_products:
      position:
        x: -179
        "y": -78
      tempMetlId: 329
    Create_table_src_prod_cost:
      position:
        x: -171
        "y": 48
      tempMetlId: 330
    And_Tables_Creation:
      position:
        x: 0
        "y": -32
      tempMetlId: 331
    RDS_src_product_cost:
      position:
        x: 144
        "y": 48
      tempMetlId: 332
    RDS_src_products:
      position:
        x: 144
        "y": -80
      tempMetlId: 333
    Rewrite_products 0:
      position:
        x: 432
        "y": -32
      tempMetlId: 334
    And_Tables_Load:
      position:
        x: 288
        "y": -32
      tempMetlId: 335
