type: "orchestration"
version: "1.0"
pipeline:
  components:
    vIew_customer_east:
      type: "sql-script"
      transitions:
        success:
        - "vIew_customer_west"
      skipped: false
      parameters:
        componentName: "vIew_customer_east"
        sqlScript: "/*READ ME:\nREPLACE \"INTERNAL_TRAINING_CANDIDATE_1\" with <your\
          \ database name>\nREPLACE \"db_source\" with <your schema>\n*/\n\nCREATE\
          \ OR REPLACE VIEW \"${job_database_name}\".\"${job_source_schema_name}\"\
          .\"VW_CUST_NAME\"\nAS\nselect \nCUSTOMER_ID CUSTNO, CUSTOMER_FIRSTNAME ||\
          \ ' ' || CUSTOMER_LASTNAME CUSTNAME,\nCUSTOMER_PHONE PHONE, CUSTOMER_ADDRESS\
          \ ADDRESS, CUSTOMER_ZIPCODE ZIP, CUSTOMER_INCOME INCOME\nfrom \"${job_database_name}\"\
          .\"${job_source_schema_name}\".\"STG_CUSTOMERS\"\nwhere \"CUSTOMER_REGION\"\
          \ = 'East';\n\n"
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "vIew_customer_east"
      skipped: false
      parameters:
        componentName: "Start 0"
    vIew_customer_west:
      type: "sql-script"
      transitions:
        success:
        - "view_customer_central"
      skipped: false
      parameters:
        componentName: "vIew_customer_west"
        sqlScript: "/*READ ME:\nREPLACE \"INTERNAL_TRAINING_CANDIDATE_1\" with <your\
          \ database name>\nREPLACE \"db_source\" with <your schema>\n*/\n\nCREATE\
          \ OR REPLACE VIEW \"${job_database_name}\".\"${job_source_schema_name}\"\
          .\"VW_CUST_NAME\"\nAS\nselect \nCUSTOMER_ID CUSTNO, CUSTOMER_FIRSTNAME ||\
          \ ' ' || CUSTOMER_LASTNAME CUSTNAME,\nCUSTOMER_PHONE PHONE, CUSTOMER_ADDRESS\
          \ ADDRESS, CUSTOMER_ZIPCODE ZIP, CUSTOMER_INCOME INCOME\nfrom \"${job_database_name}\"\
          .\"${job_source_schema_name}\".\"STG_CUSTOMERS\"\nwhere \"CUSTOMER_REGION\"\
          \ = 'East';\n\n"
    view_customer_central:
      type: "sql-script"
      skipped: false
      parameters:
        componentName: "view_customer_central"
        sqlScript: "/*READ ME:\nREPLACE \"INTERNAL_TRAINING_CANDIDATE_1\" with <your\
          \ database name>\nREPLACE \"db_source\" with <your schema>\n*/\n\nCREATE\
          \ OR REPLACE VIEW \"${job_database_name}\".\"${job_source_schema_name}\"\
          .\"VW_CUST_NAME\"\nAS\nselect \nCUSTOMER_ID CUSTNO, CUSTOMER_FIRSTNAME ||\
          \ ' ' || CUSTOMER_LASTNAME CUSTNAME,\nCUSTOMER_PHONE PHONE, CUSTOMER_ADDRESS\
          \ ADDRESS, CUSTOMER_ZIPCODE ZIP, CUSTOMER_INCOME INCOME\nfrom \"${job_database_name}\"\
          .\"${job_source_schema_name}\".\"STG_CUSTOMERS\"\nwhere \"CUSTOMER_REGION\"\
          \ = 'East';\n\n"
  variables:
    job_database_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "MKMOTORS"
    job_source_schema_name:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "PUBLIC"
design:
  components:
    vIew_customer_east:
      position:
        x: -528
        "y": 64
      tempMetlId: 320
    Start 0:
      position:
        x: -640
        "y": 64
      tempMetlId: 321
    vIew_customer_west:
      position:
        x: -384
        "y": 64
      tempMetlId: 322
    view_customer_central:
      position:
        x: -224
        "y": 64
      tempMetlId: 323
  notes:
    "317":
      position:
        x: -761
        "y": -176
      size:
        height: 122
        width: 440
      theme: "green"
      content: |-
        **READ ME**

        REMEMBER TO:
        Add the names of your database and source schema using the job variables:
        **- job_database_name
        - job_source_schema_name**

        **The job will fail if the table stg_customers doesn't exist already.**
    "318":
      position:
        x: -288
        "y": -175
      size:
        height: 123
        width: 432
      theme: "yellow"
      content: "These views will be created in the **db_source** schema"
    "319":
      position:
        x: -673
        "y": 18
      size:
        height: 98
        width: 529
      theme: "yellow"
      content: "Check the snowflake account:  [docs.snowflake.com](docs.snowflake.com)"
