type: "transformation"
version: "1.0"
pipeline:
  metadata:
    description: "Transform Dealership Data"
  components:
    STG_DEALERSHIP:
      type: "table-input"
      parameters:
        componentName: "STG_DEALERSHIP"
        database: "[Environment Default]"
        schema: "STG"
        targetTable: "STG_DEALERSHIP"
        columnNames:
        - "DEALERSHIP_ID"
        - "DEALERSHIP_MANAGER_ID"
        - "DEALERSHIP_DESC"
        - "DEALERSHIP_LOCATION"
        - "DEALERSHIP_STATE"
        - "DEALERSHIP_REGION"
        - "DEALERSHIP_COUNTRY"
        timeOffset: ""
    Calculator 0:
      type: "calculator"
      sources:
      - "STG_DEALERSHIP"
      parameters:
        componentName: "Calculator 0"
        includeInputColumns: "Yes"
        calculations:
        - - "\"DEALERSHIP_REGION\" || '.' || \"DEALERSHIP_COUNTRY\" "
          - "REG_CTRY"
        - - "UPPER(\"DEALERSHIP_STATE\")"
          - "STATE_UP"
    dm_dealer:
      type: "table-output"
      sources:
      - "Calculator 0"
      parameters:
        componentName: "dm_dealer"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "DWH"
        targetTable: "DM_DEALERSHIP"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "DEALERSHIP_ID"
          - "DLRSHIP_ID"
        - - "DEALERSHIP_MANAGER_ID"
          - "DLRSHIP_MGR_ID"
        - - "DEALERSHIP_DESC"
          - "DLRSHIP_NAME"
        - - "DEALERSHIP_LOCATION"
          - "DLRSHIP_CITY"
        - - "STATE_UP"
          - "DLRSHIP_STATE"
        - - "REG_CTRY"
          - "DLRSHIP_REG_CTRY"
        orderBy:
        - - "DLRSHIP_ID"
          - "Ascending"
        outputMode: "Append"
  variables:
    KeyValues:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          Dealer_Key:
            columnType: "NUMBER"
      defaultValue:
      - - "1"
design:
  components:
    STG_DEALERSHIP:
      position:
        x: 77
        "y": 45
      tempMetlId: 311
    Calculator 0:
      position:
        x: 218
        "y": 59
      tempMetlId: 312
    dm_dealer:
      position:
        x: 345
        "y": 70
      tempMetlId: 313
