type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Table Iterator 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    RDS Query 0:
      type: "rds-query"
      skipped: false
      parameters:
        componentName: "RDS Query 0"
        basicAdvancedMode: "Advanced"
        databaseType: "mysql"
        rdsEndpoint: "mysql-mkm.cyalkxt4axz9.us-west-2.rds.amazonaws.com:3306"
        databaseName: "srcdbu"
        username: "srcuser"
        password: ""
        sqlQuery: "select \nPAYMENT_ID,\nPAYMENT_TYPE_DESC PAYMENT_TYPE_NAME,\nCREATED_AT\n\
          from SRC_PAYMENT_TYPE\nwhere CREATED_AT > '${env_pay_maxts}'\n"
        jdbcOptions:
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SOURCE"
        targetTable: "PAYMENT_TYPE_TEMP"
        stage: "[Custom]"
        stagePlatform: "Existing Amazon S3 Location"
        stageAuthentication: "Credentials"
        s3StagingArea: "mkmotors"
        useAcceleratedEndpoint: "False"
        encryption: "None"
        concurrency: "1"
        loadOptions:
        - "On"
        - "Off"
        - "Off"
        - ""
        - "On"
        - "Gzip"
    Table Iterator 0:
      type: "table-iterator"
      transitions:
        success:
        - "load_stg_payment_inc"
      iterationTarget: "RDS Query 0"
      skipped: false
      parameters:
        componentName: "Table Iterator 0"
        mode: "Advanced"
        query: "select max(updated_ts) latest_ts from stg_payment_type"
        concurrency: "Sequential"
        columnMapping1:
        - - "LATEST_TS"
          - "env_pay_maxts"
        breakOnFailure: "No"
    load_stg_payment_inc:
      type: "run-transformation"
      skipped: false
      parameters:
        componentName: "load_stg_payment_inc"
        transformationJob: "Training_BlackCloud/load_stg_payment_inc"
        setScalarVariables:
        setGridVariables:
design:
  components:
    Start 0:
      position:
        x: -288
        "y": -16
      tempMetlId: 8783
    RDS Query 0:
      position:
        x: -112
        "y": 16
      tempMetlId: 8791
    Table Iterator 0:
      position:
        x: -112
        "y": -16
      tempMetlId: 8913
    load_stg_payment_inc:
      position:
        x: 64
        "y": -16
      tempMetlId: 9137
