type: "transformation"
version: "1.0"
pipeline:
  components:
    STG_CUSTOMERS:
      type: "table-input"
      parameters:
        componentName: "STG_CUSTOMERS"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_CUSTOMERS"
        columnNames:
        - "DEALERSHIP_ID"
        - "CUSTOMER_REGION"
        - "CUSTOMER_ID"
        - "CUSTOMER_FIRSTNAME"
        - "CUSTOMER_LASTNAME"
        - "CUSTOMER_ADDRESS"
        - "CUSTOMER_CITY"
        - "CUSTOMER_STATE"
        - "CUSTOMER_ZIPCODE"
        - "CUSTOMER_COUNTRY"
        - "CUSTOMER_PHONE"
        - "CUSTOMER_GENDER"
        - "CUSTOMER_INCOME"
        - "CUSTOMER_EMAIL"
        - "CUSTOMER_AGE"
        - "LAST_UPDATED"
        timeOffset: ""
    calc_name_gender_phone:
      type: "calculator"
      sources:
      - "Filter_Invalid_Cust_ID"
      parameters:
        componentName: "calc_name_gender_phone"
        includeInputColumns: "Yes"
        calculations:
        - - |
            "CUSTOMER_FIRSTNAME" || ' ' || "CUSTOMER_LASTNAME"
          - "OUT_NAME"
        - - "IFF (\"CUSTOMER_GENDER\"='M',\n\t\n    'MALE',\n\n\tIFF (\"CUSTOMER_GENDER\"\
            ='F',\n\t\t'FEMALE',\n\t\t 'N/A') )\n         \n"
          - "OUT_GENDER"
        - - |-
            '(' || SUBSTR("CUSTOMER_PHONE", 1,3) || ') ' ||

            SUBSTR("CUSTOMER_PHONE", 4,3) || '-' ||

            SUBSTR("CUSTOMER_PHONE", 7)
          - "OUT_PHONE"
        - - "MKMOTORS.DW.SEQ_CUST.NEXTVAL"
          - "CUST_SEQ"
    Map_Age_Group:
      type: "map-values"
      sources:
      - "calc_name_gender_phone"
      parameters:
        componentName: "Map_Age_Group"
        valueMap:
        - - "CUSTOMER_AGE"
          - "Is"
          - "Less than or equal to"
          - "21"
          - "Boys"
        - - "CUSTOMER_AGE"
          - "Is"
          - "Less than or equal to"
          - "40"
          - "Youngsters"
        - - "CUSTOMER_AGE"
          - "Is"
          - "Less than or equal to"
          - "60"
          - "MiddleAged"
        - - "CUSTOMER_AGE"
          - "Is"
          - "Greater than or equal to"
          - "80"
          - "SuperSeniors"
        columnName: "Age_Group"
        other: "Seniors"
    Filter_Invalid_Cust_ID:
      type: "filter"
      sources:
      - "STG_CUSTOMERS"
      parameters:
        componentName: "Filter_Invalid_Cust_ID"
        filterConditions:
        - - "CUSTOMER_ID"
          - "Not"
          - "Equal to"
          - "0"
        - - "CUSTOMER_ID"
          - "Not"
          - "Equal to"
          - "99999"
        - - "CUSTOMER_ID"
          - "Not"
          - "Null"
          - "Null"
        combineCondition: "AND"
    DM_CUSTOMERS:
      type: "table-output"
      sources:
      - "Map_Age_Group"
      parameters:
        componentName: "DM_CUSTOMERS"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "DW"
        targetTable: "DM_CUSTOMERS"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "CUST_SEQ"
          - "CUST_KEY"
        - - "CUSTOMER_ID"
          - "CUST_ID"
        - - "OUT_NAME"
          - "CUST_NAME"
        - - "CUSTOMER_ADDRESS"
          - "CUST_ADDRESS"
        - - "CUSTOMER_CITY"
          - "CUST_CITY"
        - - "CUSTOMER_STATE"
          - "CUST_STATE"
        - - "CUSTOMER_ZIPCODE"
          - "CUST_ZIP_CODE"
        - - "CUSTOMER_COUNTRY"
          - "CUST_COUNTRY"
        - - "OUT_PHONE"
          - "CUST_PHONE_NMBR"
        - - "OUT_GENDER"
          - "CUST_GENDER"
        - - "Age_Group"
          - "CUST_AGE_GROUP"
        - - "CUSTOMER_INCOME"
          - "CUST_INCOME"
        - - "CUSTOMER_EMAIL"
          - "CUST_EMAIL"
        - - "CUSTOMER_AGE"
          - "CUST_AGE"
        orderBy:
        outputMode: "Append"
design:
  components:
    STG_CUSTOMERS:
      position:
        x: 0
        "y": 48
      tempMetlId: 5236
    calc_name_gender_phone:
      position:
        x: 336
        "y": 48
      tempMetlId: 5304
    Map_Age_Group:
      position:
        x: 496
        "y": 48
      tempMetlId: 5353
    Filter_Invalid_Cust_ID:
      position:
        x: 176
        "y": 48
      tempMetlId: 5379
    DM_CUSTOMERS:
      position:
        x: 656
        "y": 48
      tempMetlId: 7315
