type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "S3_Emp_json"
      skipped: false
      parameters:
        componentName: "Start 0"
    S3_Emp_json:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3_Emp_json"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mkmotors/Employees/"
        pattern: ".*employees.*[1].*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SOURCE"
        targetTable: "JEMP"
        loadColumns:
        - "VC"
        format: "[Custom]"
        fileType: "JSON"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ""
        skipHeader: ""
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
design:
  components:
    Start 0:
      position:
        x: -384
        "y": -16
      tempMetlId: 7350
    S3_Emp_json:
      position:
        x: -273
        "y": -17
      tempMetlId: 7361
