type: "transformation"
version: "1.0"
pipeline:
  components:
    SQL 0:
      type: "sql"
      parameters:
        componentName: "SQL 0"
        query: "select * from stg_dates,table(datecalc(datevalue))"
    DM_DATES:
      type: "table-output"
      sources:
      - "Calculator 0"
      parameters:
        componentName: "DM_DATES"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "DW"
        targetTable: "DM_DATES"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "DKEY"
          - "DATE_KEY"
        - - "DATEID"
          - "DATE_ID_LEGACY"
        - - "DATEVALUE"
          - "DATE_VALUE"
        - - "DOM"
          - "DAY_OF_MONTH"
        - - "MON"
          - "MONTH_NUMBER"
        - - "YER"
          - "YEAR_VALUE"
        - - "DOW"
          - "DAY_OF_WEEK"
        - - "DAN"
          - "DAY_NAME"
        - - "MNM"
          - "MONTH_NAME"
        - - "DOY"
          - "DAY_OF_YEAR"
        - - "WOY"
          - "WEEK_OF_YEAR"
        - - "MOY"
          - "MONTH_OF_YEAR"
        - - "QOY"
          - "QUARTER_OF_YEAR"
        orderBy:
        outputMode: "Append"
    Calculator 0:
      type: "calculator"
      sources:
      - "SQL 0"
      parameters:
        componentName: "Calculator 0"
        includeInputColumns: "Yes"
        calculations:
        - - "MKMOTORS.DW.SEQ_DATES.NEXTVAL"
          - "DKEY"
design:
  components:
    SQL 0:
      position:
        x: 134
        "y": 66
      tempMetlId: 12523
    DM_DATES:
      position:
        x: 336
        "y": 64
      tempMetlId: 12534
    Calculator 0:
      position:
        x: 239
        "y": 67
      tempMetlId: 12557
