type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Create Table 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    Create Table 0:
      type: "create-table-v2"
      transitions:
        success:
        - "S3 Load 0"
      skipped: false
      parameters:
        componentName: "Create Table 0"
        createMethod: "Create if not exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "STG_PAYMENT_TYPE"
        snowflakeTableType: "Transient"
        columns:
        - - "PAYMENT_ID"
          - "NUMBER"
          - "5"
          - "0"
          - ""
          - "No"
          - "No"
          - ""
        - - "PAYMENT_TYPE_DESC"
          - "VARCHAR"
          - "15"
          - "0"
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation: ""
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
    S3 Load 0:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load 0"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mkmotors/"
        pattern: "Temp/payment_type.dat"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_PAYMENT_TYPE"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "True"
        fieldOptionallyEnclosed: "\""
        nullIf:
        - - ""
        errorOnColumnCountMismatch: "True"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
design:
  components:
    Start 0:
      position:
        x: -624
        "y": -64
      tempMetlId: 391
    Create Table 0:
      position:
        x: -523
        "y": -61
      tempMetlId: 392
    S3 Load 0:
      position:
        x: -373
        "y": -61
      tempMetlId: 393
