type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "File Iterator 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    Data Transfer 0:
      type: "data-transfer-object"
      skipped: false
      parameters:
        componentName: "Data Transfer 0"
        sourceType: "S3"
        sourceUrl5: "s3://mkmotors/Sources/${env_filname}"
        unpackZipFile: "No"
        targetType: "S3"
        gzipData: "No"
        targetObjectName: "${env_filname}"
        targetUrl2: "s3://mkmotors/Customers/"
        accessControlListOptions: ""
        encryption: "None"
    S3 Load 0:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load 0"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://mkmotors/Customers/"
        pattern: ".*${env_region_names}.*"
        encryption: "None"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_CUSTOMERS"
        loadColumns:
        - "DEALERSHIP_ID"
        - "CUSTOMER_REGION"
        - "CUSTOMER_ID"
        - "CUSTOMER_FIRSTNAME"
        - "CUSTOMER_LASTNAME"
        - "CUSTOMER_ADDRESS"
        - "CUSTOMER_CITY"
        - "CUSTOMER_STATE"
        - "CUSTOMER_ZIPCODE"
        - "CUSTOMER_COUNTRY"
        - "CUSTOMER_PHONE"
        - "CUSTOMER_GENDER"
        - "CUSTOMER_INCOME"
        - "CUSTOMER_EMAIL"
        - "CUSTOMER_AGE"
        - "LAST_UPDATED"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ""
        skipHeader: "1"
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: "\""
        nullIf:
        - - ""
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Continue"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    File Iterator 0:
      type: "file-iterator"
      transitions:
        success:
        - "Fixed Iterator 0"
      iterationTarget: "Data Transfer 0"
      skipped: false
      parameters:
        componentName: "File Iterator 0"
        inputDataType: "S3"
        inputDataUrl1: "s3://mkmotors/Sources/"
        inputDataUrl3: "Yes"
        maxIterations: "25"
        filterRegex: ".*customers[.]dat.*"
        concurrency: "Sequential"
        variables:
        - - "env_filname"
          - "Filename"
        breakOnFailure: "No"
    Fixed Iterator 0:
      type: "fixed-iterator"
      iterationTarget: "S3 Load 0"
      skipped: false
      parameters:
        componentName: "Fixed Iterator 0"
        concurrency: "Sequential"
        variablesToIterate:
        - "env_region_names"
        iterationValues:
        - - "east"
        - - "central"
        - - "west"
        breakOnFailure: "No"
design:
  components:
    Start 0:
      position:
        x: -416
        "y": 0
      tempMetlId: 405
    Data Transfer 0:
      position:
        x: -304
        "y": -48
      tempMetlId: 406
    S3 Load 0:
      position:
        x: -169
        "y": -56
      tempMetlId: 407
    File Iterator 0:
      position:
        x: -304
        "y": -48
      tempMetlId: 408
    Fixed Iterator 0:
      position:
        x: -169
        "y": -56
      tempMetlId: 409
