type: "transformation"
version: "1.0"
pipeline:
  components:
    PAYMENT_TYPE_TEMP:
      type: "table-input"
      parameters:
        componentName: "PAYMENT_TYPE_TEMP"
        database: "[Environment Default]"
        schema: "SOURCE"
        targetTable: "PAYMENT_TYPE_TEMP"
        columnNames:
        - "PAYMENT_ID"
        - "PAYMENT_TYPE_NAME"
        - "CREATED_AT"
        timeOffset: ""
    STG_PAYMENT_TYPE:
      type: "table-update"
      sources:
      - "PAYMENT_TYPE_TEMP"
      parameters:
        componentName: "STG_PAYMENT_TYPE"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_PAYMENT_TYPE"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"target\".\"PAYMENT_ID\"=\"input\".\"PAYMENT_ID\""
          - "Join"
        whenMatched:
        - - "\"target\".\"PAYMENT_TYPE_NAME\"!=\"input\".\"PAYMENT_TYPE_NAME\""
          - "Update"
        updateMapping:
        - - "PAYMENT_TYPE_NAME"
          - "PAYMENT_TYPE_NAME"
        - - "CREATED_AT"
          - "UPDATED_TS"
        includeNotMatched: "Yes"
        insertMapping:
        - - "PAYMENT_ID"
          - "PAYMENT_ID"
        - - "PAYMENT_TYPE_NAME"
          - "PAYMENT_TYPE_NAME"
        - - "CREATED_AT"
          - "UPDATED_TS"
design:
  components:
    PAYMENT_TYPE_TEMP:
      position:
        x: -96
        "y": 80
      tempMetlId: 9059
    STG_PAYMENT_TYPE:
      position:
        x: 250
        "y": 75
      tempMetlId: 9072
