type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Azure Blob Storage Load 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    Azure Blob Storage Load 0:
      type: "azure-blob-storage-load"
      skipped: false
      parameters:
        componentName: "Azure Blob Storage Load 0"
        stage: "[Custom]"
        authentication: "Storage Integration"
        storageIntegration: "AZURE_INT_MKM"
        azureStorageLocation: "azure://mktstorage123.blob.core.windows.net/mkmotors-sf/Sources/"
        pattern: ".*dates.*"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_DATES"
        loadColumns:
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ""
        skipHeader: ""
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
design:
  components:
    Start 0:
      position:
        x: -384
        "y": 0
      tempMetlId: 12406
    Azure Blob Storage Load 0:
      position:
        x: -269
        "y": 0
      tempMetlId: 12411
