type: "transformation"
version: "1.0"
pipeline:
  components:
    create_view_prod_scd:
      type: "create-view"
      sources:
      - "join_prods_groups"
      parameters:
        componentName: "create_view_prod_scd"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        viewName: "VW_PROD_SCD_MAT"
        secureView: "No"
        viewType: "Standard"
    calc_prod_stream:
      type: "calculator"
      sources:
      - "stream_products"
      parameters:
        componentName: "calc_prod_stream"
        includeInputColumns: "Yes"
        calculations:
        - - "IFF(\n\"METADATA$ACTION\"='INSERT' AND \"METADATA$ISUPDATE\" = TRUE ,'U',\
            \ \nIFF(\"METADATA$ACTION\"='INSERT' AND \"METADATA$ISUPDATE\" = FALSE\
            \ ,'I', \nIFF(\"METADATA$ACTION\"='DELETE' AND \"METADATA$ISUPDATE\" =\
            \ FALSE ,'D','')))\n"
          - "ACTION"
        - - "'9999-12-31 00:00:00.000'::timestamp_ltz"
          - "EXPIRYTIME"
        - - "current_timestamp()"
          - "CURTIME"
        - - "FALSE"
          - "CURFLAG"
    STG_PRODGROUPS:
      type: "table-input"
      parameters:
        componentName: "STG_PRODGROUPS"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_PRODGROUPS"
        columnNames:
        - "GROUP_ID"
        - "GROUPNAME"
        - "DIVISION"
        timeOffset: ""
    join_prods_groups:
      type: "join"
      sources:
      - "STG_PRODGROUPS"
      - "calc_prod_stream"
      parameters:
        componentName: "join_prods_groups"
        mainTable: "calc_prod_stream"
        mainTableAlias: "main"
        joins:
        - - "STG_PRODGROUPS"
          - "grp"
          - "Inner"
        joinExpressions:
        - - "\"main\".\"GROUP_ID\"=\"grp\".\"GROUP_ID\""
          - "main_Inner_grp"
        columnMappings:
        - - "main.PRODUCT_ID"
          - "PRODUCT_ID"
        - - "main.GROUP_ID"
          - "GROUP_ID"
        - - "main.PRODUCT"
          - "PRODUCT"
        - - "main.PRODCOST"
          - "PRODCOST"
        - - "main.UPDATE_TS"
          - "UPDATE_TS"
        - - "main.ACTION"
          - "ACTION"
        - - "main.EXPIRYTIME"
          - "EXPIRYTIME"
        - - "main.CURTIME"
          - "CURTIME"
        - - "main.CURFLAG"
          - "CURFLAG"
        - - "grp.GROUPNAME"
          - "GROUPNAME"
        - - "grp.DIVISION"
          - "DIVISION"
    stream_products:
      type: "stream-input-sf"
      parameters:
        componentName: "stream_products"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetStream: "STR_PRODUCTS"
        columnNames:
        - "PRODUCT_ID"
        - "GROUP_ID"
        - "PRODUCT"
        - "PRODCOST"
        - "UPDATE_TS"
        - "METADATA$ACTION"
        - "METADATA$ISUPDATE"
design:
  components:
    create_view_prod_scd:
      position:
        x: 496
        "y": -16
      tempMetlId: 11078
    calc_prod_stream:
      position:
        x: 128
        "y": 96
      tempMetlId: 11079
    STG_PRODGROUPS:
      position:
        x: -48
        "y": -16
      tempMetlId: 11080
    join_prods_groups:
      position:
        x: 336
        "y": -16
      tempMetlId: 11081
    stream_products:
      position:
        x: -48
        "y": 96
      tempMetlId: 11082
