type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start Product SCD Load:
      type: "start"
      transitions:
        unconditional:
        - "create_stream_stg_products"
      skipped: false
      parameters:
        componentName: "Start Product SCD Load"
    begin_transaction_scd_load:
      type: "begin"
      transitions:
        success:
        - "products_scd_load 0"
      skipped: false
      parameters:
        componentName: "begin_transaction_scd_load"
    products_scd_load 0:
      type: "run-transformation"
      transitions:
        success:
        - "make_all_changes_permanent_dm_products"
        failure:
        - "reject_the_changes_dm_products"
      skipped: false
      parameters:
        componentName: "products_scd_load 0"
        transformationJob: "Training_BlackCloud/products_scd_load"
        setScalarVariables:
        setGridVariables:
    make_all_changes_permanent_dm_products:
      type: "commit"
      skipped: false
      parameters:
        componentName: "make_all_changes_permanent_dm_products"
    reject_the_changes_dm_products:
      type: "rollback"
      skipped: false
      parameters:
        componentName: "reject_the_changes_dm_products"
    create_stream_stg_products:
      type: "create-stream"
      transitions:
        success:
        - "create_prod_scd_view"
      skipped: false
      parameters:
        componentName: "create_stream_stg_products"
        createReplace: "Create if not exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        streamName: "STR_PRODUCTS"
        tableDatabase: "[Environment Default]"
        tableSchema: "[Environment Default]"
        table: "STG_PRODUCTS"
        appendOnly: "False"
    create_prod_scd_view:
      type: "run-transformation"
      transitions:
        success:
        - "begin_transaction_scd_load"
      skipped: false
      parameters:
        componentName: "create_prod_scd_view"
        transformationJob: "Samples/test_SubJob_Products_SCD_02"
        setScalarVariables:
        setGridVariables:
design:
  components:
    Start Product SCD Load:
      position:
        x: -656
        "y": 0
      tempMetlId: 11003
    begin_transaction_scd_load:
      position:
        x: -144
        "y": -80
      tempMetlId: 11004
    products_scd_load 0:
      position:
        x: 32
        "y": -48
      tempMetlId: 11005
    make_all_changes_permanent_dm_products:
      position:
        x: 208
        "y": -96
      tempMetlId: 11006
    reject_the_changes_dm_products:
      position:
        x: 32
        "y": 80
      tempMetlId: 11007
    create_stream_stg_products:
      position:
        x: -464
        "y": -64
      tempMetlId: 11051
    create_prod_scd_view:
      position:
        x: -288
        "y": 32
      tempMetlId: 11052
