type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Create Table 0"
        - "API Extract 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    py_mon_names:
      type: "python-script"
      skipped: false
      parameters:
        componentName: "py_mon_names"
        script: "###\n# Variables are directly accessible: \n#   print myvar\n# Updating\
          \ a variable:\n#   context.updateVariable('myvar', 'new-value')\n# Grid\
          \ Variables are accessible via the context:\n#   print context.getGridVariable('mygridvar')\n\
          # Udating a grid variable:\n#   context.updateGridVariable('mygridvar',\
          \ [['list','of'],['lists','!']])\n# A database cursor can be accessed from\
          \ the context (Jython only):\n#   cursor = context.cursor()\n#   cursor.execute('select\
          \ count(*) from mytable')\n#   rowcount = cursor.fetchone()[0]\n###\n# print\
          \ 'Month Number:', job_mno, 'Month Name:', job_mnm\n\nprint context.getGridVariable('grid_Dates')\n\
          \n"
        interpreter: "Python 3"
    Create Table 0:
      type: "create-table-v2"
      transitions:
        success:
        - "Azure Blob Storage Load 0"
      skipped: false
      parameters:
        componentName: "Create Table 0"
        createMethod: "Create if not exists"
        database: "[Environment Default]"
        schema: "SOURCE"
        table: "SRC_DATES"
        snowflakeTableType: "Transient"
        columns:
        - - "Date_ID"
          - "NUMBER"
          - "8"
          - "0"
          - ""
          - "No"
          - "No"
          - ""
        - - "Date_Value"
          - "DATE"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
        defaultDdlCollation: ""
        primaryKeys:
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: ""
    Query Result To Grid 0:
      type: "query-to-grid"
      transitions:
        success:
        - "Grid Iterator 0"
      skipped: false
      parameters:
        componentName: "Query Result To Grid 0"
        mode: "Basic"
        database: "[Environment Default]"
        schema: "SOURCE"
        table: "SRC_DATES"
        tableColumns:
        - "Date_ID"
        - "Date_Value"
        orderBy:
        sort: "Ascending"
        limit: "10"
        gridVariable: "grid_Dates"
        gridVariableMapping:
        - - "Date_ID"
          - "D_No"
        - - "Date_Value"
          - "D_Val"
        filterConditions:
        combineConditions: "AND"
    Grid Iterator 0:
      type: "grid-iterator"
      iterationTarget: "py_mon_names"
      skipped: false
      parameters:
        componentName: "Grid Iterator 0"
        gridVariable: "grid_Dates"
        gridIteratorVariableMapping:
        - - "D_No"
          - "env_month_no"
        - - "D_Val"
          - "env_month_name"
        breakOnFailure: "No"
        concurrency: "Sequential"
    Azure Blob Storage Load 0:
      type: "azure-blob-storage-load"
      transitions:
        success:
        - "Query Result To Grid 0"
      skipped: false
      parameters:
        componentName: "Azure Blob Storage Load 0"
        stage: "[Custom]"
        authentication: "Credentials"
        azureStorageLocation: "azure://mktstorage123.blob.core.windows.net/mkmotors-sf/"
        pattern: ".*"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_DATES"
        loadColumns:
        - "DATEID"
        - "DATEVALUE"
        format: "[Custom]"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ""
        skipHeader: ""
        skipBlankLines: "False"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace: "False"
        fieldOptionallyEnclosed: ""
        nullIf:
        errorOnColumnCountMismatch: "False"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "False"
        encodingType: ""
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    API Extract 0:
      type: "unknown-orchestration"
      transitions:
        success:
        - "End Success 0"
      skipped: false
      parameters:
        "1": "API Extract 0"
        "2": "Conversion"
        "3": "Production"
        "4": "default"
        "5": "currency"
        "6": "Task History_auth"
        "7": ""
        "8": "ec2-user"
        "9": ""
        "10": ""
        "11": "1"
        "12":
        "13":
          "1":
          - - "pairs"
            - "USDINR"
        "14":
        "15": ""
        "16": ""
        "17": ""
        "18": ""
        "22": "Conversion"
        "113": "s3://mkmotors/Mat_Stage/"
        "114": "[Environment Default]"
        "115": "[Environment Default]"
        "116": "[Environment Default]"
        "117": "STG_SAMPLES"
        "118": ""
    End Success 0:
      type: "end-success"
      skipped: false
      parameters:
        componentName: "End Success 0"
  variables:
    job_mnm:
      metadata:
        type: "TEXT"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "Jan"
    job_mno:
      metadata:
        type: "NUMBER"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
      defaultValue: "1"
    grid_Dates:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          D_No:
            columnType: "NUMBER"
          D_Val:
            columnType: "TEXT"
      defaultValue: []
    grid_Month_Names:
      metadata:
        type: "GRID"
        description: ""
        scope: "COPIED"
        visibility: "PUBLIC"
        columns:
          Month_No:
            columnType: "NUMBER"
          Month_Name:
            columnType: "TEXT"
      defaultValue:
      - - "1"
        - "January"
      - - "2"
        - "February"
      - - "3"
        - "March"
      - - "4"
        - "April"
      - - "5"
        - "May"
      - - "6"
        - "June"
      - - "7"
        - "July"
      - - "8"
        - "August"
      - - "9"
        - "September"
      - - "10"
        - "October"
      - - "11"
        - "November"
      - - "12"
        - "December"
design:
  components:
    Start 0:
      position:
        x: -1680
        "y": -336
      tempMetlId: 304
    py_mon_names:
      position:
        x: -1120
        "y": -320
      tempMetlId: 518
    Create Table 0:
      position:
        x: -1552
        "y": -336
      tempMetlId: 698
    Query Result To Grid 0:
      position:
        x: -1264
        "y": -352
      tempMetlId: 1096
    Grid Iterator 0:
      position:
        x: -1120
        "y": -352
      tempMetlId: 1132
    Azure Blob Storage Load 0:
      position:
        x: -1424
        "y": -336
      tempMetlId: 1958
    API Extract 0:
      position:
        x: -1552
        "y": -240
      tempMetlId: 12056
    End Success 0:
      position:
        x: -1424
        "y": -243
      tempMetlId: 12114
