type: "transformation"
version: "1.0"
pipeline:
  components:
    JEMP:
      type: "table-input"
      parameters:
        componentName: "JEMP"
        database: "[Environment Default]"
        schema: "SOURCE"
        targetTable: "JEMP"
        columnNames:
        - "VC"
        timeOffset: ""
    Extract_JEmp:
      type: "extract-nested-data-sf"
      sources:
      - "JEMP"
      parameters:
        componentName: "Extract_JEmp"
        includeInputColumns: "Yes"
        columns:
        - name: "address"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "address"
          isArray: "false"
          include: "false"
          childElements:
          - name: "city"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "city"
            isArray: "false"
            include: "true"
          - name: "street"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "street"
            isArray: "false"
            include: "true"
          - name: "zip"
            datatype: "NUMBER"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "zip"
            isArray: "false"
            include: "true"
          - name: "state"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "state"
            isArray: "false"
            include: "true"
        - name: "date_entered"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "date_entered"
          isArray: "false"
          include: "true"
        - name: "dealership"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "dealership"
          isArray: "false"
          include: "false"
          childElements:
          - name: "id"
            datatype: "NUMBER"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "dealership_id"
            isArray: "false"
            include: "true"
          - name: "region"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "region"
            isArray: "false"
            include: "true"
        - name: "email"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "email"
          isArray: "false"
          include: "true"
        - name: "employee"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "employee"
          isArray: "false"
          include: "false"
          childElements:
          - name: "firstname"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "firstname"
            isArray: "false"
            include: "true"
          - name: "gender"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "gender"
            isArray: "false"
            include: "true"
          - name: "id"
            datatype: "NUMBER"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "employee_id"
            isArray: "false"
            include: "true"
          - name: "lastname"
            datatype: "VARCHAR"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "lastname"
            isArray: "false"
            include: "true"
          - name: "age"
            datatype: "NUMBER"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "age"
            isArray: "false"
            include: "true"
        - name: "hire_date"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "hire_date"
          isArray: "false"
          include: "true"
        - name: "phone"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "phone"
          isArray: "false"
          include: "false"
          childElements:
          - name: "fixed"
            datatype: "NUMBER"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "fixed"
            isArray: "false"
            include: "true"
          - name: "mobile"
            datatype: "NUMBER"
            size: "0"
            decimalPlaces: "0"
            columnName: "VC"
            aliasName: "mobile"
            isArray: "false"
            include: "true"
        - name: "position"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "VC"
          aliasName: "position"
          isArray: "false"
          include: "true"
        outerJoin: "False"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Replace unparseable dates and timestamps with null"
        caseColumnAliasNames: "Upper"
    STG_EMPLOYEES:
      type: "table-output"
      sources:
      - "Join 0"
      parameters:
        componentName: "STG_EMPLOYEES"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_EMPLOYEES"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "EMPLOYEE_ID"
          - "EMPLOYEE_ID"
        - - "EMPLOYEE_FIRST_NAME"
          - "EMPLOYEE_FIRST_NAME"
        - - "EMPLOYEE_LAST_NAME"
          - "EMPLOYEE_LAST_NAME"
        - - "EMPLOYEE_ADDRESS"
          - "EMPLOYEE_ADDRESS"
        - - "EMPLOYEE_CITY"
          - "EMPLOYEE_CITY"
        - - "EMPLOYEE_STATE"
          - "EMPLOYEE_STATE"
        - - "EMPLOYEE_ZIP_CODE"
          - "EMPLOYEE_ZIP_CODE"
        - - "EMPLOYEE_MOBILE"
          - "EMPLOYEE_MOBILE"
        - - "EMPLOYEE_FIXEDLINE"
          - "EMPLOYEE_FIXEDLINE"
        - - "EMPLOYEE_EMAIL"
          - "EMPLOYEE_EMAIL"
        - - "EMPLOYEE_GENDER"
          - "EMPLOYEE_GENDER"
        - - "EMPLOYEE_AGE"
          - "EMPLOYEE_AGE"
        - - "POSITION_TYPE"
          - "POSITION_TYPE"
        - - "DEALERSHIP_ID"
          - "DEALERSHIP_ID"
        - - "SALARY"
          - "SALARY"
        - - "DEALERSHIP_MANAGER"
          - "DEALERSHIP_MANAGER"
        - - "REGION"
          - "REGION"
        - - "HIRED_DATE"
          - "HIRE_DATE"
        - - "DATE_ENTERED"
          - "DATE_ENTERED"
        orderBy:
        outputMode: "Append"
    Join 0:
      type: "join"
      sources:
      - "Extract_S3_Salary"
      - "Extract_JEmp"
      parameters:
        componentName: "Join 0"
        mainTable: "Extract_JEmp"
        mainTableAlias: "Main"
        joins:
        - - "Extract_S3_Salary"
          - "Sal"
          - "Inner"
        joinExpressions:
        - - "\"Main\".\"employee_id\"=\"Sal\".\"EMP_ID\""
          - "Main_Inner_Sal"
        columnMappings:
        - - "Main.employee_id"
          - "EMPLOYEE_ID"
        - - "Main.firstname"
          - "EMPLOYEE_FIRST_NAME"
        - - "Main.lastname"
          - "EMPLOYEE_LAST_NAME"
        - - "Main.street"
          - "EMPLOYEE_ADDRESS"
        - - "Main.city"
          - "EMPLOYEE_CITY"
        - - "Main.state"
          - "EMPLOYEE_STATE"
        - - "Main.zip"
          - "EMPLOYEE_ZIP_CODE"
        - - "Main.mobile"
          - "EMPLOYEE_MOBILE"
        - - "Main.fixed"
          - "EMPLOYEE_FIXEDLINE"
        - - "Main.email"
          - "EMPLOYEE_EMAIL"
        - - "Main.gender"
          - "EMPLOYEE_GENDER"
        - - "Main.age"
          - "EMPLOYEE_AGE"
        - - "Main.position"
          - "POSITION_TYPE"
        - - "Main.dealership_id"
          - "DEALERSHIP_ID"
        - - "Sal.SALARY"
          - "SALARY"
        - - "Main.region"
          - "REGION"
        - - "Main.hire_date"
          - "HIRED_DATE"
        - - "Main.date_entered"
          - "DATE_ENTERED"
        - - "Sal.MANAGER"
          - "DEALERSHIP_MANAGER"
    Extract_S3_Salary:
      type: "sql"
      parameters:
        componentName: "Extract_S3_Salary"
        query: "select $1 Emp_ID,$2 Salary, 'Manager' Manager from @s3_sense"
design:
  components:
    JEMP:
      position:
        x: 176
        "y": 96
      tempMetlId: 6227
    Extract_JEmp:
      position:
        x: 384
        "y": 144
      tempMetlId: 6426
    STG_EMPLOYEES:
      position:
        x: 832
        "y": 48
      tempMetlId: 6476
    Join 0:
      position:
        x: 624
        "y": 64
      tempMetlId: 6538
    Extract_S3_Salary:
      position:
        x: 336
        "y": -16
      tempMetlId: 6546
