type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "RDS Query 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    RDS Query 0:
      type: "rds-query"
      skipped: false
      parameters:
        componentName: "RDS Query 0"
        basicAdvancedMode: "Advanced"
        databaseType: "mysql"
        rdsEndpoint: "mysql-mkm.cyalkxt4axz9.us-west-2.rds.amazonaws.com:3306"
        databaseName: "srcdbu"
        username: "srcuser"
        password: ""
        sqlQuery: "select \nPAYMENT_ID, \nPAYMENT_TYPE_DESC PAYMENT_TYPE_NAME,\nCREATED_AT\n\
          from SRC_PAYMENT_TYPE where CREATED_AT < '${env_pay_maxts}'"
        jdbcOptions:
        type: "Standard"
        primaryKeys:
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "SOURCE"
        targetTable: "SRC_PAYMENT_TYPE"
        stage: "[Custom]"
        stagePlatform: "Existing Amazon S3 Location"
        stageAuthentication: "Credentials"
        s3StagingArea: "mkmotors"
        useAcceleratedEndpoint: "False"
        encryption: "None"
        concurrency: "1"
        loadOptions:
        - "On"
        - "Off"
        - "Off"
        - ""
        - "On"
        - "Gzip"
design:
  components:
    Start 0:
      position:
        x: -816
        "y": -80
      tempMetlId: 7663
    RDS Query 0:
      position:
        x: -642
        "y": -76
      tempMetlId: 8117
