type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Retry 0"
      skipped: false
      parameters:
        componentName: "Start 0"
    Retry 0:
      type: "retry"
      iterationTarget: "RDS Bulk Output 0"
      skipped: false
      parameters:
        componentName: "Retry 0"
        numberOfRetries: "10"
        retryDelay: "Long delay with backoff"
    RDS Bulk Output 0:
      type: "rds-bulk-output"
      skipped: false
      parameters:
        componentName: "RDS Bulk Output 0"
        rdsType: "mysql"
        rdsEndpoint: "mysql-mkm.cyalkxt4axz9.us-west-2.rds.amazonaws.com:3306"
        databaseName: "srcdbu"
        username: "srcuser"
        password: ""
        jdbcOptions:
        database: "[Environment Default]"
        schema: "[Environment Default]"
        sourceTable: "STG_PAYMENT_ENCRYPT"
        targetTable: "OUT_PAY_ENCRYPT"
        loadColumns:
        - "PAYMENT_ID"
        - "PAYMENT_TYPE"
        tableMaintenance: "Create If Not Exists"
        primaryKey:
        truncateTargetTable: "No"
        onWarnings: "Continue"
        additionalCopyOptions: ""
        batchSize: ""
design:
  components:
    Start 0:
      position:
        x: 0
        "y": 0
      tempMetlId: 11591
    Retry 0:
      position:
        x: 125
        "y": -71
      tempMetlId: 11619
    RDS Bulk Output 0:
      position:
        x: 125
        "y": -71
      tempMetlId: 11643
